// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/api.proto

package go_micro_api_example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pair struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values               []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pair) Reset()         { *m = Pair{} }
func (m *Pair) String() string { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()    {}
func (*Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{0}
}

func (m *Pair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pair.Unmarshal(m, b)
}
func (m *Pair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pair.Marshal(b, m, deterministic)
}
func (m *Pair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pair.Merge(m, src)
}
func (m *Pair) XXX_Size() int {
	return xxx_messageInfo_Pair.Size(m)
}
func (m *Pair) XXX_DiscardUnknown() {
	xxx_messageInfo_Pair.DiscardUnknown(m)
}

var xxx_messageInfo_Pair proto.InternalMessageInfo

func (m *Pair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Pair) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

// 一个Http请求
type Request struct {
	Method               string           `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path                 string           `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Header               map[string]*Pair `protobuf:"bytes,3,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Get                  map[string]*Pair `protobuf:"bytes,4,rep,name=get,proto3" json:"get,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Post                 map[string]*Pair `protobuf:"bytes,5,rep,name=post,proto3" json:"post,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 string           `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Url                  string           `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Request) GetHeader() map[string]*Pair {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Request) GetGet() map[string]*Pair {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *Request) GetPost() map[string]*Pair {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *Request) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Request) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// 一个Http响应
type Response struct {
	StatusCode           int32            `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Header               map[string]*Pair `protobuf:"bytes,2,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 string           `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *Response) GetHeader() map[string]*Pair {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Response) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

// 一个Http事件
type Event struct {
	// e.g login
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// uuid
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// unix timestamp of event
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// event headers
	Header map[string]*Pair `protobuf:"bytes,4,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// the event data
	Data                 string   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{3}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Event) GetHeader() map[string]*Pair {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Event) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*Pair)(nil), "go.micro.api.example.Pair")
	proto.RegisterType((*Request)(nil), "go.micro.api.example.Request")
	proto.RegisterMapType((map[string]*Pair)(nil), "go.micro.api.example.Request.GetEntry")
	proto.RegisterMapType((map[string]*Pair)(nil), "go.micro.api.example.Request.HeaderEntry")
	proto.RegisterMapType((map[string]*Pair)(nil), "go.micro.api.example.Request.PostEntry")
	proto.RegisterType((*Response)(nil), "go.micro.api.example.Response")
	proto.RegisterMapType((map[string]*Pair)(nil), "go.micro.api.example.Response.HeaderEntry")
	proto.RegisterType((*Event)(nil), "go.micro.api.example.Event")
	proto.RegisterMapType((map[string]*Pair)(nil), "go.micro.api.example.Event.HeaderEntry")
}

func init() { proto.RegisterFile("proto/api.proto", fileDescriptor_ecf0878b123623e2) }

var fileDescriptor_ecf0878b123623e2 = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0xbd, 0x76, 0xd2, 0x4c, 0x24, 0x40, 0x23, 0x84, 0x56, 0x11, 0x54, 0x51, 0x0e, 0x10,
	0x38, 0x98, 0x2a, 0x5c, 0x2a, 0x38, 0x20, 0x5a, 0x02, 0x48, 0x5c, 0xa2, 0x45, 0x7c, 0xc0, 0x16,
	0x8f, 0x1a, 0x0b, 0x3b, 0x6b, 0xbc, 0xeb, 0x8a, 0x7c, 0x08, 0x1f, 0xc7, 0x87, 0x70, 0x47, 0x3b,
	0xde, 0xa6, 0x3d, 0xa4, 0xbe, 0xb4, 0xbd, 0xbd, 0x1d, 0xef, 0x7b, 0x9e, 0x37, 0x6f, 0x6c, 0x78,
	0x58, 0x37, 0xc6, 0x99, 0xd7, 0xba, 0x2e, 0x32, 0x46, 0xf8, 0xf8, 0xdc, 0x64, 0x55, 0xf1, 0xa3,
	0x31, 0x99, 0xaf, 0xd1, 0x6f, 0x5d, 0xd5, 0x25, 0xcd, 0x8e, 0x20, 0x59, 0xe9, 0xa2, 0xc1, 0x47,
	0x20, 0x7e, 0xd2, 0x56, 0x46, 0xd3, 0x68, 0x3e, 0x52, 0x1e, 0xe2, 0x13, 0x18, 0x5c, 0xe8, 0xb2,
	0x25, 0x2b, 0xe3, 0xa9, 0x98, 0x8f, 0x54, 0x38, 0xcd, 0xfe, 0x24, 0x30, 0x54, 0xf4, 0xab, 0x25,
	0xeb, 0xfc, 0x9d, 0x8a, 0xdc, 0xda, 0xe4, 0x81, 0x18, 0x4e, 0x88, 0x90, 0xd4, 0xda, 0xad, 0x65,
	0xcc, 0x55, 0xc6, 0xf8, 0x01, 0x06, 0x6b, 0xd2, 0x39, 0x35, 0x52, 0x4c, 0xc5, 0x7c, 0xbc, 0x78,
	0x99, 0xed, 0x6b, 0x28, 0x0b, 0xd2, 0xd9, 0x17, 0xbe, 0xbb, 0xdc, 0xb8, 0x66, 0xab, 0x02, 0x11,
	0x8f, 0x41, 0x9c, 0x93, 0x93, 0x09, 0xf3, 0x9f, 0xf7, 0xf3, 0x3f, 0x93, 0xeb, 0xc8, 0x9e, 0x82,
	0xef, 0x20, 0xa9, 0x8d, 0x75, 0x32, 0x65, 0xea, 0x8b, 0x7e, 0xea, 0xca, 0xd8, 0xc0, 0x65, 0x92,
	0x77, 0x73, 0x66, 0xf2, 0xad, 0x1c, 0x74, 0x6e, 0x3c, 0xf6, 0xf3, 0x6a, 0x9b, 0x52, 0x0e, 0xbb,
	0x79, 0xb5, 0x4d, 0x39, 0xf9, 0x0e, 0xe3, 0x6b, 0x3d, 0xef, 0x19, 0xe8, 0x11, 0xa4, 0x3c, 0x42,
	0x9e, 0xca, 0x78, 0x31, 0xd9, 0xdf, 0x84, 0x4f, 0x43, 0x75, 0x17, 0xdf, 0xc6, 0xc7, 0xd1, 0x44,
	0xc1, 0xc1, 0xa5, 0x95, 0x3b, 0xd3, 0xfc, 0x06, 0xa3, 0x9d, 0xc7, 0xbb, 0x12, 0x9d, 0xfd, 0x8d,
	0xe0, 0x40, 0x91, 0xad, 0xcd, 0xc6, 0x12, 0x1e, 0x02, 0x58, 0xa7, 0x5d, 0x6b, 0x4f, 0x4d, 0x4e,
	0xac, 0x9d, 0xaa, 0x6b, 0x15, 0x3c, 0xd9, 0x2d, 0x43, 0xcc, 0x89, 0xbc, 0xba, 0x29, 0x91, 0x4e,
	0x6f, 0xef, 0x36, 0x5c, 0xc6, 0x22, 0xae, 0x62, 0xb9, 0xa7, 0x10, 0x66, 0xff, 0x22, 0x48, 0x97,
	0x17, 0xb4, 0xe1, 0x5d, 0xd8, 0xe8, 0x8a, 0x82, 0x24, 0x63, 0x7c, 0x00, 0x71, 0x91, 0x87, 0x5d,
	0x8f, 0x8b, 0x1c, 0x9f, 0xc2, 0xc8, 0x15, 0x15, 0x59, 0xa7, 0xab, 0x9a, 0xbb, 0x13, 0xea, 0xaa,
	0x80, 0xef, 0x77, 0xd6, 0x93, 0xbe, 0x65, 0xe4, 0xd7, 0xdd, 0xe4, 0x3b, 0xd7, 0x4e, 0xcb, 0xb4,
	0x6b, 0xc1, 0xe3, 0x7b, 0xf2, 0xbd, 0x58, 0xc1, 0x70, 0xd9, 0x3d, 0xc2, 0x25, 0x24, 0xa7, 0xba,
	0x2c, 0xf1, 0x59, 0xef, 0xb7, 0x33, 0x39, 0xec, 0x0f, 0x72, 0xf1, 0x15, 0xc4, 0x27, 0x63, 0xf0,
	0x23, 0x88, 0x13, 0xdd, 0xdc, 0x52, 0xec, 0x6c, 0xc0, 0x7f, 0xb6, 0x37, 0xff, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x92, 0xf9, 0x6c, 0x40, 0xec, 0x04, 0x00, 0x00,
}
